version: 2
jobs:
  modules:
    docker:
      - image: gebish/ci:v6
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-modules
      - run: ./gradlew --no-daemon --max-workers 2 --parallel -p module -Pci check --continue
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home-modules
          paths:
            - .gradle-home
  compatibility:
    docker:
      - image: gebish/ci:v6
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-compatibility
      - run: ./gradlew --no-daemon --max-workers 2 --parallel -p compatibility -Pci check --continue
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home-compatibility
          paths:
            - .gradle-home
  integrations:
    docker:
      - image: gebish/ci:v6
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-integrations
      - run: ./gradlew --no-daemon --max-workers 2 --parallel -p integration -Pci check --continue
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home-integrations
          paths:
            - .gradle-home
  manual:
    docker:
      - image: gebish/ci:v6
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-manual
      - run:
          command: |
            Xvfb :99 -screen 1 1280x1024x16 -nolisten tcp -fbdir /var/run > /dev/null 2>&1 &
            export DISPLAY=:99
            ./gradlew --no-daemon --max-workers 2 --parallel -Pci :doc:manual-snippets:check :doc:manual:build
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home-manual
          paths:
            - .gradle-home
  site:
    docker:
      - image: gebish/ci:v6
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-site
      - run: ./gradlew --no-daemon --max-workers 2 --parallel -p doc/site -Pci check
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home-site
          paths:
            - .gradle-home
  saucelabs:
    docker:
      - image: gebish/ci:v6
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-saucelabs
      - run:
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              ./gradlew --no-daemon -Pci allSauceLabsTests
            fi
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home-saucelabs
          paths:
            - .gradle-home
  non-ie:
    docker:
      - image: gebish/ci:v6
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-non-ie
      - run:
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              ./gradlew --no-daemon -Pci nonIeBrowserStackTests
            fi
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home-non-ie
          paths:
            - .gradle-home
  ie:
    docker:
      - image: gebish/ci:v6
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-ie
      - run:
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              ./gradlew --no-daemon -Pci ieBrowserStackTests
            fi
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home-ie
          paths:
            - .gradle-home
  upload:
    docker:
      - image: gebish/ci:v6
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home-upload
      - run:
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              ./gradlew --no-daemon -Pci uploadArchives
            fi
      - save_cache:
          key: gradle-home-upload
          paths:
            - .gradle-home
  publish-site:
    docker:
      - image: gebish/ci:v6
    steps:
      - checkout
      - run:
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/gebish.git
              git push -f heroku master
            fi
  trigger-example-projects:
    docker:
      - image: gebish/ci:v6
    steps:
      - run:
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              curl -X POST -u ${CIRCLE_API_EXAMPLE_GRADLE_TOKEN}: https://circleci.com/api/v1.1/project/github/geb/geb-example-gradle/tree/latest
              curl -X POST -u ${CIRCLE_API_EXAMPLE_CUCUMBER_JVM_TOKEN}: https://circleci.com/api/v1.1/project/github/geb/geb-example-cucumber-jvm/tree/latest
              curl -X POST -u ${CIRCLE_API_EXAMPLE_MAVEN_TOKEN}: https://circleci.com/api/v1.1/project/github/geb/geb-example-maven/tree/latest
              curl -H "Authorization: Bearer ${APPVEYOR_TOKEN}" -H "Content-type: application/json" -X POST https://ci.appveyor.com/api/builds -d '{"accountName": "erdi", "projectSlug": "geb-example-gradle", "branch": "latest"}'
            fi

workflows:
  version: 2
  build-workflow:
    jobs:
      - modules
      - compatibility
      - integrations:
          requires:
            - modules
            - compatibility
      - manual:
          requires:
            - modules
            - compatibility
      - site:
          requires:
            - modules
            - compatibility
      - saucelabs:
          requires:
            - integrations
            - manual
            - site
      - non-ie:
          requires:
            - integrations
            - manual
            - site
      - ie:
          requires:
            - non-ie
      - upload:
          requires:
            - saucelabs
            - ie
          filters:
            branches:
              only: master
      - publish-site:
          requires:
            - upload
          filters:
            branches:
              only: master
      - trigger-example-projects:
          requires:
            - upload
          filters:
            branches:
              only: master